### ISSUE TITLE
如何本地运行

### ISSUE THREAD

**Issue by bugroom** [DokiYoloo/CareUEveryDay#18]
大佬请问下若不用Github Actions，怎么本地运行，需要注释掉代码中哪部分关联内容

**Comment by DokiYoloo** [comment]
本地运行 如果没有开发经验不太建议哈 

需要本地安装java环境 以及maven环境
需要用maven 打包后 通过java -jar运行
或者简单就使用IDE 直接运行 比如 IDEA
