### ISSUE TITLE
无法推送Read timed out

### ISSUE THREAD

**Issue by Gxyloj** [DokiYoloo/CareUEveryDay#21]
![QQ截图20221025090506](https://user-images.githubusercontent.com/48832052/197658414-892e1ba9-5f3c-4cc9-bd37-1d3c2f155fc3.png)
已经换了自己的高德api-key测试过没有问题，过一段时间以后定时任务的话必报错，无法推送.但是本地运行main是没有问题的。在GitHub action上无论是推送运行还是定时都会报这个错误

**Comment by DokiYoloo** [comment]
Github服务器因为机房不在国内请求古诗或高德api有时候确实会超时

**Comment by DokiYoloo** [comment]
已加大超时时间  此issue将关闭  
请参考  
[commit1](https://github.com/DokiYoloo/CareUEveryDay/commit/738a277cc019aa919de2661f1282566dd6c587fb)  
[commit2](https://github.com/DokiYoloo/CareUEveryDay/commit/772bacc271e702e8db874eb896e1c04b760f5ab1)
