### ISSUE TITLE
修改cron表达式 更改定时任务没有效果

### ISSUE THREAD

**Issue by c1139676919** [DokiYoloo/CareUEveryDay#22]

**Comment by DokiYoloo** [comment]
可以截图贴下代码看下

**Comment by c1139676919** [comment]
> 
百度了一手  说github这个定时是按当时定时任务顺序来执行的 资源有限  会延迟一段时间

**Comment by c1139676919** [comment]
> > 
> 
> 百度了一手 说github这个定时是按当时定时任务顺序来执行的 资源有限 会延迟一段时间

https://www.nuomiphp.com/t/616b9fc4f026713b8630ca9e.html

**Comment by c1139676919** [comment]
> 可以截图贴下代码看下


百度了一手 说github这个定时是按当时定时任务顺序来执行的 资源有限 会延迟一段时间

https://www.nuomiphp.com/t/616b9fc4f026713b8630ca9e.html

**Comment by DokiYoloo** [comment]
> 

是的，这个调度是会有一定的延迟
还有个需要注意的是 GithubActions使用的UTC时间 转换为北京时间需要-8小时处理

**Comment by DokiYoloo** [comment]
> > 可以截图贴下代码看下
> 
> 百度了一手 说github这个定时是按当时定时任务顺序来执行的 资源有限 会延迟一段时间
> 
> https://www.nuomiphp.com/t/616b9fc4f026713b8630ca9e.html

是的，这个调度是会有一定的延迟
还有个需要注意的是 GithubActions使用的UTC时间 转换为北京时间需要-8小时处理
