### ISSUE TITLE
Maven错误

### ISSUE THREAD

**Issue by TeQuieroS** [DokiYoloo/CareUEveryDay#23]
错误：编译错误：
[信息] -------------------------------------------------------------
错误：/home/runner/work/raindrop/raindrop/src/main/java/cn/ofpp/core/MessageFactory.java:[4,15]找不到符号
符号：类Bootstrap
位置：package cn.ofpp
错误：/home/runner/work/raindrop/raindrop/src/main/java/cn/ofpp/core/Wx.java:[3,15]找不到符号
符号：类Bootstrap
位置：package cn.ofpp
错误：/home/runner/work/raindrop/raindrop/src/main/java/cn/ofpp/Application.java:[26,9] 找不到符号
符号：变量引导
位置：类cn.ofpp.Application
错误：/home/runner/work/raindrop/raindrop/src/main/java/cn/ofpp/core/MessageFactory.java:[22,76]找不到符号
符号：变量引导
位置：类cn.ofpp.core.MessageFactory
错误：/home/runner/work/raindrop/raindrop/src/main/java/cn/ofpp/core/Wx.java:[22,27] 找不到符号
符号：变量引导
地点：cn.ofpp.core.Wx类
错误：/home/runner/work/raindrop/raindrop/src/main/java/cn/ofpp/core/Wx.java:[23,28] 找不到符号
符号：变量引导
地点：cn.ofpp.core.Wx类
[信息] 6个错误

**Comment by DokiYoloo** [comment]
可以检查下有修改的地方
这个一般是修改时改错了东西 
编译时报了错误
