### ISSUE TITLE
sendWxTemplatemsg提示报错：Read timed out

### ISSUE THREAD

**Issue by Fuzzy-Zhang** [DokiYoloo/CareUEveryDay#24]
定时任务执行，但偶尔会出现sendWxTemplatemsg报错：Error: Exception in thread "main" cn.hutool.core.io.IORuntimeException: SocketTimeoutException: Read timed out，出现当天无法正常推送

**Comment by Fuzzy-Zhang** [comment]
> 定时任务执行，但偶尔会出现sendWxTemplatemsg报错：Error: Exception in thread "main" cn.hutool.core.io.IORuntimeException: SocketTimeoutException: Read timed out，出现当天无法正常推送

**Comment by DokiYoloo** [comment]
可以尝试拉下最新的代码，已加长超时时间~

如果依然存在相关问题 可以将代码中的 读取超时时间 再进行加长
由于github服务器在国外 api的相关接口服务器在国内 概率性会出现此问题

**Comment by Fuzzy-Zhang** [comment]
> 可以尝试拉下最新的代码，已加长超时时间~
> 
> 如果依然存在相关问题 可以将代码中的 读取超时时间 再进行加长 由于github服务器在国外 api的相关接口服务器在国内 概率性会出现此问题

请问您提及的读取超时时间是在哪个文件下

**Comment by DokiYoloo** [comment]
> > 可以尝试拉下最新的代码，已加长超时时间~
> > 如果依然存在相关问题 可以将代码中的 读取超时时间 再进行加长 由于github服务器在国外 api的相关接口服务器在国内 概率性会出现此问题
> 
> 请问您提及的读取超时时间是在哪个文件下

[GaodeUtil.java](https://github.com/DokiYoloo/CareUEveryDay/blob/master/src/main/java/cn/ofpp/core/GaodeUtil.java)
在此文件内 单位是毫秒~

**Comment by Fuzzy-Zhang** [comment]
> > > 可以尝试拉下最新的代码，已加长超时时间~
> > > 如果依然存在相关问题 可以将代码中的 读取超时时间 再进行加长 由于github服务器在国外 api的相关接口服务器在国内 概率性会出现此问题
> > 
> > 
> > 请问您提及的读取超时时间是在哪个文件下
> 
> [GaodeUtil.java](https://github.com/DokiYoloo/CareUEveryDay/blob/master/src/main/java/cn/ofpp/core/GaodeUtil.java) 在此文件内 单位是毫秒~

收到，感谢耐心回复~
