### ISSUE TITLE
定时任务设置没有反应

### ISSUE THREAD

**Issue by Git-liuxiaoyu** [DokiYoloo/CareUEveryDay#9]
![image](https://user-images.githubusercontent.com/81342043/186406630-0a5841f0-24a4-434b-b5ad-970e85eeedb7.png)
![image](https://user-images.githubusercontent.com/81342043/186406679-533b2d76-315d-4365-8700-f74cd0c750fe.png)

**Comment by DokiYoloo** [comment]
第一个表达式不行哦
github限制最少5分钟执行一次 3分钟不行

**Comment by Git-liuxiaoyu** [comment]
已解决
